# -*- coding: utf-8 -*-
"""halo_dunia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJLLNbLoszllfJm5UvMap7ov2W5ajeXm
"""

print("Hello World")

